### ISSUE TITLE
Pan gesture dismissing does not work correctly with blurring on iOS 10

### ISSUE THREAD

**Issue by MohammadAG** [m1entus/MZFormSheetPresentationController#101]
When panning to dismiss on iOS 10 on a controller with a blur effect applied, the animation glitches.
I'm almost sure that this is because dimmingView's alpha is being changed (UIVisualEffectView should always have an alpha of 1.0).

An ideal fix is to use alpha on iOS 8, but for iOS 9 and above, use an animation block to animate UIVisualEffectView's effect property between nil and UIBlurEffect to achieve a blur animation.

I could only get this to work when it slides up on its own, however, I couldn't figure out how to do it for interactive transitions.

Anyway, to test this, use the example provided on the repo but add
`formSheetController.presentationController.shouldApplyBackgroundBlurEffect = YES;
    formSheetController.presentationController.blurEffectStyle = UIBlurEffectStyleLight;`
to - (void)panGestureDismissingGesture.

**Comment by MohammadAG** [comment]
Here's a recording of the bug (zipped because Github doesn't support MOV), in case you don't have iOS 10 installed.

[bug.zip](https://github.com/m1entus/MZFormSheetPresentationController/files/417045/bug.zip)

**Comment by m1entus** [comment]
iOS10 still in beta, i will check on GM

**Comment by aabulhaj** [comment]
This seems to be affecting my app on iOS 10 GM, has there been any progress?

**Comment by m1entus** [comment]
If i have some time i will look on it

**Comment by m1entus** [comment]
Fixed, i will release new version soon
