### ISSUE TITLE
incorrect instructions

### ISSUE THREAD

**Issue by asehgal123** [m1entus/MZFormSheetPresentationController#102]
yo,

in readme.md installation instructions says to import using following line:
#import \<MZFormSheetPresentationController/MZFormSheetPresentationViewControllerFramework.h>

it should read as:
#import \<MZFormSheetPresentationController/MZFormSheetPresentationControllerFramework.h>

Spent an hour figuring out, why it wasn't finding the file. :)

**Comment by m1entus** [comment]
Can you correct it and make pr ?
