### ISSUE TITLE
Presenting in modal controller

### ISSUE THREAD

**Issue by viktoricalonia** [m1entus/MZFormSheetPresentationController#106]
Is it possible to present FormSheet in a modal controller like https://github.com/m1entus/MZFormSheetController.? Is there a workaround that will let us present  FormSheet in a modal ViewController? Thanks in advance.

**Comment by m1entus** [comment]
"Is it possible to present FormSheet in a modal controller" what do you mean by this ?

**Comment by viktoricalonia** [comment]
What i mean is, MZFormSheetPresentationController can't present ViewController on top of a model ViewController (view controller that is presented with `-presentViewController:animated:completion`. Unlike the deprecated `MZFormSheetController` that can still present ViewControlle on top of a modal controller. Is there any work around of this in MZFormSheetPresentationController. If none, maybe i will just use the `MZFormSheetController`

**Comment by m1entus** [comment]
It can but you have to present from view controller which is presented on top
