### ISSUE TITLE
Minor addition to README

### ISSUE THREAD

**Issue by acegreen** [m1entus/MZFormSheetPresentationController#107]
First off, many thanks for this, great work.. I came across something interesting. 
1. Use storyboard to create segue
2. Give it the class name and identifier, set to Kind: custom 

When I segue directly to a UIViewController, prepareForSegue was not being called. I had to embed in a UINavigationController for it to be called. 

prepareForSegue if you use a regular form sheet presentation

Would be nice to add this to the README for future reference

**Comment by m1entus** [comment]
Can you make PR ?

**Comment by acegreen** [comment]
Yea I can do that. Did you confirm this behaviour and whether it's intended or not?
