### ISSUE TITLE
contentViewSize with rotation

### ISSUE THREAD

**Issue by acegreen** [m1entus/MZFormSheetPresentationController#108]
Currently I have my contentViewSize setup as such

`presentationSegue.formSheetPresentationController.presentationController?.contentViewSize = CGSize(width: self.view.bounds.size.width, height: 450)`

I would like that to hold true while rotating the size. So my view is always full width. 

Thanks in advance

**Comment by m1entus** [comment]
Check examples there is an answer for that...

**Comment by acegreen** [comment]
Dziękuję...But can you be a little more specific. There are quit a few example and the ones I looked at, I didn't catch anything

**Comment by acegreen** [comment]
@m1entus this? If so, this requires me to handle rotation myself. Any reason why the library doesn't adjust size during rotation?

```
        formSheetController.presentationController?.frameConfigurationHandler = { [weak formSheetController] view, currentFrame, isKeyboardVisible in
            if UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication().statusBarOrientation) {
                return CGRectMake(CGRectGetMidX(formSheetController!.presentationController!.containerView!.bounds) - 210, currentFrame.origin.y, 420, currentFrame.size.height)
            }
            return currentFrame
        };
```

**Comment by acegreen** [comment]
Nix all that.. got it working. I'll list it for future reference:

1. Make your UINavigationController conform to MZFormSheetContentSizingNavigationController
2.  Make your UIViewController conform to MZFormSheetPresentationContentSizing
3. implement the following delegate functions

```
    public func shouldUseContentViewFrame(for presentationController: MZFormSheetPresentationController!) -> Bool {
        return true
    }
    
    func contentViewFrame(for presentationController: MZFormSheetPresentationController!, currentFrame: CGRect) -> CGRect {
        
        var currentFrame = currentFrame
        currentFrame.size.width = Constants.application.keyWindow!.bounds.size.width
        return currentFrame
    }
```

In my case, I wanted the width to always be my windows width.

**Comment by m1entus** [comment]
👍

**Comment by eliburke** [comment]
Because reasons, I display a UIImagePickerController in a full screen modal form sheet. Something about this configuration causes problems during autorotation-- the imagePicker detects rotation, but the bounds do not change from portrait to landscape and vice versa.

In case anyone needs to fix the bounds of a system view controller, it can be done in a category without subclassing:

```
// category to add content sizing behavior
@interface UIImagePickerController (modalRotate) <MZFormSheetPresentationContentSizing>
@end

@implementation UIImagePickerController (modalRotate)
- (BOOL)shouldUseContentViewFrameForPresentationController:(MZFormSheetPresentationController *)presentationController {
    return YES;
}
- (CGRect)contentViewFrameForPresentationController:(MZFormSheetPresentationController *)presentationController currentFrame:(CGRect)currentFrame {
    return [UIScreen mainScreen].bounds;
}
@end
```

**Comment by JeffreyCA** [comment]
Thank you @acegreen!

FYI:

You implement the delegate functions in the UIViewController which conforms to `MZFormSheetPresentationContentSizing`. I did something like this:

```swift
import MZFormSheetPresentationController
...
class CustomUIViewController: UIViewController {
    ...
}

extension CustomUIViewController: MZFormSheetPresentationContentSizing {
    func shouldUseContentViewFrame(for presentationController: MZFormSheetPresentationController!) -> Bool {
        return true
    }

    func contentViewFrame(for presentationController: MZFormSheetPresentationController!, currentFrame: CGRect) -> CGRect {
        var currentFrame = currentFrame
        currentFrame.size.width = Constants.application.keyWindow!.bounds.size.width
        return currentFrame
    }
}



```
