### ISSUE TITLE
Preset animations not working correctly

### ISSUE THREAD

**Issue by FridaySG** [m1entus/MZFormSheetPresentationController#109]
let dialog = MZFormSheetPresentationViewController(contentViewController: vc)
            dialog.presentationController?.contentViewSize = CGSizeMake(300, 235)
            dialog.presentationController?.shouldCenterHorizontally = true
            dialog.presentationController?.shouldCenterVertically = true
            dialog.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyle.Fade

Fade becomes SlideAndBounceFromTop. Some are mixed, while some don't work at all. For example, DropDown is impossible to use now.

**Comment by m1entus** [comment]
Only in example files, normally is working

**Comment by m1entus** [comment]
Working fine using example:
```
func presentFormSheetControllerWithTransition(transition: Int) {
        let navigationController = self.formSheetControllerWithNavigationController()
        let formSheetController = MZFormSheetPresentationViewController(contentViewController: navigationController)
        formSheetController.presentationController?.shouldDismissOnBackgroundViewTap = true
        formSheetController.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyle.Fade
        
        self.presentViewController(formSheetController, animated: MZFormSheetPresentationTransitionStyle(rawValue: transition)! != .None, completion: nil)
    }
```
