### ISSUE TITLE
support iOS 7?

### ISSUE THREAD

**Issue by chenyuan** [m1entus/MZFormSheetPresentationController#11]
does this support iOS 7? running the example on a iPhone 4 iOS 7.x, I got this
![screen shot 2015-07-23 at 4 48 30 pm](https://cloud.githubusercontent.com/assets/334233/8844641/cb9afa54-315a-11e5-8cf8-40ee1b871aaf.png)

**Comment by m1entus** [comment]
If you want to support iOS7 use this one: https://github.com/m1entus/MZFormSheetController
