### ISSUE TITLE
iOS10 view appears off-screen

### ISSUE THREAD

**Issue by ehlersd** [m1entus/MZFormSheetPresentationController#113]
When presented normally, I have one VC that is displaying and while the MZFormSheetPresentationViewController's frame origin looks fine, my VC that the MZ is created with, has it's origin.y set to -180....

Any ideas where to look?

**Comment by ehlersd** [comment]
@m1entus Any ideas?

**Comment by AlbertoLourenco** [comment]
Same problem here.

**Comment by m1entus** [comment]
No idea, check transition ?
