### ISSUE TITLE
Changing BlurRadius

### ISSUE THREAD

**Issue by gintechsystems** [m1entus/MZFormSheetPresentationController#114]
Is changing the blur radius no longer possible with MZFormSheet? I know the older version used to allow this but I don't see the option anymore. I know we are using the native blur but I don't see why the option would not be available?

**Comment by m1entus** [comment]
No it is not possible, this was causing some bugs so i have decided to native blur

**Comment by gintechsystems** [comment]
Alright, thank you for letting me know. What bugs were occurring? I only ever had one that was an easy fix, I was supporting iOS 7 or newer though. I don't know if it would be rejected from the app store but I may just go back to the old version if I need to use it again.
