### ISSUE TITLE
Passing data back from the PresentationController

### ISSUE THREAD

**Issue by hat8** [m1entus/MZFormSheetPresentationController#117]
Hello,

**Briefly**: I have a ViewController A and a MZFormSheetPresentationController B (TableView), and I want to **pass data back** from B -> A. 
I already tried to use several methods like protocol, delegate, unwind segue etc, but it seems that there is no effect. 
As I am new to Swift and iOS, I'm not sure if it's because I didn't find the right method. Thank you very much for helping.

**More details**: On my ViewController A, there is a button which present a MZFormSheetPresentationController B, just as in the example given:

> ```
> @IBAction func withWhoPop(sender: UIButton) {
>     let navigationController = self.storyboard!.instantiateViewControllerWithIdentifier("Navigation") as! UINavigationController
>     let formSheetController = MZFormSheetPresentationViewController(contentViewController: navigationController)
>    formSheetController.presentationController?.shouldDismissOnBackgroundViewTap = true
>     formSheetController.presentationController?.contentViewSize = CGSizeMake(300, 500) 
>     self.presentViewController(formSheetController, animated: true, completion: nil)
> }
> ```

B is a TableView, and each row corresponds to a group.
Each row has: a label (name of the group), and a button (which leads to a distinct tableView C. C contains the elements of the corresponding group).

Once the used has selected a row in B, I want to pass the name of the row back to A, and replace the label of the button on A by this name.

Thank you very much for your reading time, and I would be grateful if you could give me some indication. I tried for several days and don't see what I can do now.

**Comment by hat8** [comment]
Sorry, may I ask if it is closed because my question is not relevant...? 
Thanks

**Comment by m1entus** [comment]
You have to implement standard delegate, or block pattern with callback, MZFormSheetPrenestationController is only for presentation rest you have to do by yourself and there is no difference with behaviour between this and standard one. I would recomment you to ask a question on stackoverflow

**Comment by hat8** [comment]
Thank you very much for your kind confirmation, I will try again.
