### ISSUE TITLE
didDismissContentViewControllerHandler

### ISSUE THREAD

**Issue by Simone67** [m1entus/MZFormSheetPresentationController#119]
Hello,
I can't find any example about using in SWIFT:
MZFormSheetPresentationViewControllerCompletionHandler didDismissContentViewControllerHandler

in objective-C I used this line, what's the equivalent in Swift?:
formSheetController.didDismissContentViewControllerHandler = ^(id p){ //do something ; };

thank you for your support

**Comment by GeeksDeck** [comment]
Hi, this works
formSheetController.didDismissContentViewControllerHandler =  { viewController in 
//do something
}
