### ISSUE TITLE
Pod Install Failing specifically on this repo

### ISSUE THREAD

**Issue by rtsbtate** [m1entus/MZFormSheetPresentationController#12]
Resolving dependencies of `Podfile`
	[!] Unable to satisfy the following requirements:

	- `MZFormSheetPresentationController (= 1.1.1)` required by `Podfile`

	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/resolver.rb:56:in `resolve'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:59:in `section'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:209:in `analyze'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:131:in `block in resolve_dependencies'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:59:in `section'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:130:in `resolve_dependencies'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:103:in `install!'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:101:in `run'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/lib/cocoapods/command.rb:48:in `run'
	/Users/btate/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.38.1/bin/pod:44:in `<top (required)>'
	/Users/btate/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
	/Users/btate/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
	/Users/btate/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/btate/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by rtsbtate** [comment]
I have 13 other pods that are installing fine.  It's just specifically this one that won't install.

**Comment by btate** [comment]
pod try works just fine but for some reason I can't install it in my podfile.

**Comment by ay8s** [comment]
Had similar issues with the newer versions of Cocoapods. Which version of Cocoapods are you both using? Can't see anything in particular wrong with the podspec.
