### ISSUE TITLE
'MZAppearance/MZAppearance.h' file not found

### ISSUE THREAD

**Issue by hzorr** [m1entus/MZFormSheetPresentationController#122]
Hi, it started to get 'MZAppearance/MZAppearance.h' file not found error in  MZFormSheetPresentationViewController.h on line 27, when I updated cocoapods to 1.1.1 version and it reinstalled pods. 
How to solve this issue?

**Comment by Mozahler** [comment]
I solved it by double-clicking on the .xcworkspace file: MZFormSheetPresentationController-master/Example/Swift/MZFormSheetPresentationController Swift Example.xcworkspace
