### ISSUE TITLE
Text size based on size class

### ISSUE THREAD

**Issue by mbcoder17** [m1entus/MZFormSheetPresentationController#13]
In one of my VC's that I am displaying with MZFormSheetPresentationController, I have a label whose font is based on the devices size class. However, when the form sheet is displayed the font size does not change based on the content size of the form sheet. How can I change this?

**Comment by m1entus** [comment]
This will be soon fixed, on develop i have new version of MZFormSheetPresentationController, which will be released.

**Comment by m1entus** [comment]
Fixed in MZFormSheetPresentationController 2.0.0.
