### ISSUE TITLE
App crashing on MZFormSheetPresentationController setDidTapOnBackgroundViewCompletionHandler

### ISSUE THREAD

**Issue by sgup77** [m1entus/MZFormSheetPresentationController#134]
whenever i try to set the appearance like this
MZFormSheetPresentationController.appearance().didTapOnBackgroundViewCompletionHandler = ```
{ [weak self](location) in
                self?.delegate?.closeBtnClicked(dismissButtonId, lastPageID: self?.lastPageID)
            }
```
It crashes when i present the controller again
<img width="1178" alt="screen shot 2017-06-13 at 11 57 48 am" src="https://user-images.githubusercontent.com/5609616/27119210-9228029e-50fc-11e7-957f-eacb3736405d.png">
<img width="1178" alt="screen shot 2017-06-13 at 11 57 48 am" src="https://user-images.githubusercontent.com/5609616/27119221-9e229b0e-50fc-11e7-925e-083cd53ea38c.png">

**Comment by m1entus** [comment]
didTapOnBackgroundViewCompletionHandler is not available in appearance proxy.
