### ISSUE TITLE
presenting another view?

### ISSUE THREAD

**Issue by pranjalsatija** [m1entus/MZFormSheetPresentationController#14]
If I present an MZFormSheet, and then present another view using the MZFormSheet, the MZFormSheet dismisses itself. Is there a way to prevent this?

EDIT: It doesn't actually dismiss itself, but the dismiss animation is performed.

**Comment by m1entus** [comment]
MZFormSheetPresentationController works as presenting modally in iOS, if you want to replace view which is below presenting view controller it is immposible without dismissing view controlelr from top

**Comment by pranjalsatija** [comment]
Alright. I decided to fix it by presenting the form sheet that appears as soon as it presents the other view. Thank you for the help.
