### ISSUE TITLE
Doesn't move to top when show keyboard on iOS 11

### ISSUE THREAD

**Issue by jinthreek89** [m1entus/MZFormSheetPresentationController#145]
Hi, Amazing owner.
I have setup to move to top popup view when show keyboard like bellow.
`formSheetController.presentationController.movementActionWhenKeyboardAppears = MZFormSheetActionWhenKeyboardAppearsAlwaysAboveKeyboard;`
This was working very well on iOS 10.
But this is not working correctly on iOS 11.
I attached screenshot.
![image](https://user-images.githubusercontent.com/5479567/30934873-819b8222-a401-11e7-8eb6-92702be42c9c.png)
I need help urgently because the app is stand on AppStore.

**Comment by m1entus** [comment]
But what is the issue with form sheet ? I see that this is above keyboard, iOS change scrolling probably, so you need to handle it by yourself

**Comment by jinthreek89** [comment]
Center screen is default screen.
First screen is state of showing keyboard on iOS 10. It is moving to top on keyboard.
But last screen is state of showing keyboard on iOS 11. **It is not moving to top on keyboard.**
Only cutting screen.
Should I scroll this screen manually?

**Comment by m1entus** [comment]
Feel free to debug it and make PR if you fix it

**Comment by jinthreek89** [comment]
Sorry, This issue seems like happen by IQKeyboardManager.
Thanks for your kindly support. I will close this issue.
