### ISSUE TITLE
Autolayout buttons

### ISSUE THREAD

**Issue by mbcoder17** [m1entus/MZFormSheetPresentationController#15]
I am having an issue displaying a formsheet with 2 buttons vertically spaced (evenly, centered horizontally). I want the buttons to have a minimum height of 50 each. I cannot seem to accomplish this in a formsheet with the default size. Each time I run I get a message saying all constraints cannot be satisfied. Can you lead me in the right direction/post a sample project of how I can display these buttons in the formsheet?

**Comment by m1entus** [comment]
This will be soon fixed, on develop i have new version of MZFormSheetPresentationController, which will be released.

**Comment by m1entus** [comment]
Fixed in MZFormSheetPresentationController 2.0.0.

**Comment by mbcoder17** [comment]
What was the fix for this? How can I implement it the way I want? Do I just do things as I normally would and it will be taken care of?

**Comment by m1entus** [comment]
Yes
