### ISSUE TITLE
Xcode 9.0.1 Warning: MZTransition.h "This block declaration is not a prototype"

### ISSUE THREAD

**Issue by funnel20** [m1entus/MZFormSheetPresentationController#151]
When I run Xcode 9.0.1 Analyzer with the new recommend project settings I receive the following warning in version 2.4.1:

> MZFormSheetPresentationController/MZTransition.h:32:46: This block declaration is not a prototype.

Line 32:
`typedef void (^MZTransitionCompletionHandler)();`

This can be solved easily by applying the suggested Xcode fix to add `void`:
`typedef void (^MZTransitionCompletionHandler)(void);`

**Comment by natanrolnik** [comment]
This should be solved by #153 (I've opened initially in my own fork 😬, latest is the correct PR)

**Comment by SwordJason** [comment]
Could someone helps on release a version of this?
