### ISSUE TITLE
Autoresizing breaking autolayout constraints to container view

### ISSUE THREAD

**Issue by francisykl** [m1entus/MZFormSheetPresentationController#16]
As depicts in the screenshots below, the uiviewcontroller seems to ignore the constraints for leading and trailing space. Everything is working fine after i disable autolayout it seems. Perhaps it could be caused by UIViewAutoResizing__

1. Constraints set for top, left, right 
<img width="886" alt="screen shot 2015-07-29 at 3 33 45 pm" src="https://cloud.githubusercontent.com/assets/8480611/8952215/b503684c-3607-11e5-98b6-51ac2978d420.png">
2. Landscape
<img width="611" alt="screen shot 2015-07-29 at 3 36 40 pm" src="https://cloud.githubusercontent.com/assets/8480611/8952216/b509703e-3607-11e5-8923-5a087842b81d.png">
3.Potrait
<img width="347" alt="screen shot 2015-07-29 at 3 36 57 pm" src="https://cloud.githubusercontent.com/assets/8480611/8952217/b50b5b38-3607-11e5-967b-619c29d34c5a.png">

**Comment by m1entus** [comment]
This will be soon fixed, on develop i have new version of MZFormSheetPresentationController, which will be released.

**Comment by m1entus** [comment]
Fixed in MZFormSheetPresentationController 2.0.0.
