### ISSUE TITLE
Cocoa pod supported?

### ISSUE THREAD

**Issue by rustanacexd** [m1entus/MZFormSheetPresentationController#2]
I am confused on what I need to install/copy to use this. I downloaded the example project and I see two pod dependencies.

**Comment by m1entus** [comment]
This library has two dependencies
  s.dependency 'MZAppearance'
  s.dependency 'JGMethodSwizzler'
To use it you can use Cocoapods and include MZFormSheetPresentationController or get sources of this libraries and include it to project.

**Comment by rustanacexd** [comment]
Ahh I see. ok thank you very much!
