### ISSUE TITLE
Dismissing a view displaying over view presented with MZFormSheetPresentationController reveals missing parent.

### ISSUE THREAD

**Issue by ay8s** [m1entus/MZFormSheetPresentationController#20]
Hey @m1entus.

Not sure if you've seen this one before but also seeing it when presenting another view using MZFormSheetPresentationController. 

When presenting the new view the presenting view animates out but doesn't seem to come back when dismissing the child modal.

Video: http://cl.ly/051F0Q2m3e3V

Dug into this a little but couldn't find the route cause of it.

**Comment by ay8s** [comment]
For MZFormSheetPresentationTransitionStyleSlideFromBottom it looks like the originalFormSheetRect gets set to the dismissed frame and so the modal doesn't get animated back in as the frame remains offscreen.

**Comment by ay8s** [comment]
Not sure how best to handle this case, I've currently duplicated the slide transition and added a call to setupFormSheetViewControllerFrame, which corrects the frame before the animation back in. I'm sure there's a better solution though.

**Comment by m1entus** [comment]
Not sure about it, actually i am little bit busy, when i will find some free time and motivation i will review issues and try to fix it :) Anyway thanks for reporting!

**Comment by nitinhayaran** [comment]
+1

**Comment by m1entus** [comment]
I made temporary fix to it, but in future i will have to change it.

**Comment by m1entus** [comment]
Fully fixed in 2.0.0

**Comment by ghasim** [comment]
Hey @ay8s
how to show full view size in MZFormSheetPresentationController?

Thank's
