### ISSUE TITLE
Background turns light grey instead of blurred? 

### ISSUE THREAD

**Issue by Jules2010** [m1entus/MZFormSheetPresentationController#21]
Hi,

I have exactly the same issue that I have with MZFormSheetController.

https://github.com/m1entus/MZFormSheetController/issues/182

I've adding my viewcontroller to my navigation controller programmatically, rather than with my storyboard, although I don't know why that should make a difference.

I now have.

Any ideas?
```
UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];

nav.navigationBarHidden = YES;

MZFormSheetPresentationController *formSheetController = 
    [[MZFormSheetPresentationController alloc] 
     initWithContentViewController:nav];
formSheetController.shouldApplyBackgroundBlurEffect = YES;
formSheetController.blurEffectStyle = UIBlurEffectStyleExtraLight;
// To set blur effect color, but uglty animation
//    formSheetController.backgroundColor = [[UIColor redColor] colorWithAlphaComponent:0.8];

[self presentViewController:formSheetController animated:YES completion:nil];


```

**Comment by Jules2010** [comment]
I fixed this problem with MZFormSheetController maybe the same applies here.

**Comment by Jules2010** [comment]
I'd like to re-open this as it doesn't matter what I do I have the same problem.

If I set shouldApplyBackgroundBlurEffect = YES I get a light grey color, if I don't set it, it respects the blurEffectStyle value. I'm using iOS 8.

Please help me.

:(

Thanks in advance.

**Comment by manumax** [comment]
Since `MZFormSheetPresentationController` relies on `UIVisualEffectView ` to show blurred background,  you're getting that grey background because your device (real or emulated) does not support blurring (see http://stackoverflow.com/questions/26411227/detect-if-device-properly-displays-uivisualeffectview).

**Comment by m1entus** [comment]
Thanks for explanation. I am closing it.

**Comment by JosephZZ** [comment]
it's still the case for me. my Base SDK is 9.2 and targeting 8.0, but still only have a dimming light instead of blurry effect

**Comment by m1entus** [comment]
You will never get blur using UIVisualEffect on ipad 2 and iphone 4, ios version does,t matter because this devices don't support blur...

**Comment by Jules2010** [comment]
I used marypopin instead, think it may provide its own blur effect for those devices, can't recall

**Comment by m1entus** [comment]
Yes it is possible using snapshot and blurry it but i don't wont implement it only for those devices

**Comment by JosephZZ** [comment]
it was running on iPhone 6s and it didn't blur
<img width="363" alt="screen shot 2016-02-07 at 8 18 50 pm" src="https://cloud.githubusercontent.com/assets/6688628/12878351/30e0af7a-cdd8-11e5-95a9-68046700dd0f.png">

**Comment by JosephZZ** [comment]
i just found out it was a problem else where in my own code. sorry for the trouble and thanks for trying to help!

**Comment by natanrolnik** [comment]
@JosephZZ what was the problem?

**Comment by JosephZZ** [comment]
@natanrolnik I missed a line of code that the document specifies. It was setting some value to true I think.

**Comment by dworak** [comment]
When you turn on option in iPhone Settings called: Reduce Transparency for better contrast and readability you're gonna loose the blur effects.
