### ISSUE TITLE
Swift example not building

### ISSUE THREAD

**Issue by lakamsani** [m1entus/MZFormSheetPresentationController#24]
https://github.com/m1entus/MZFormSheetPresentationController/tree/master/Example/Swift isn't building with XCode 7. Any suggestions?

==
CompileSwift normal i386 /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/CustomTransition.swift
    cd /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/TransparentViewController.swift" "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/ViewController.swift" -primary-file "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/CustomTransition.swift" "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/AppDelegate.swift" "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/PresentedTableViewController.swift" -target i386-apple-ios8.3 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -I /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator -F /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator -F /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator/Pods -g -import-objc-header "/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/MZFormSheetPresentationController/MZFormSheetPresentationController Swift Example-Bridging-Header.h" -module-cache-path /Users/vamsee/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc "-I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/swift-overrides.hmap" -Xcc -iquote -Xcc "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-generated-files.hmap" -Xcc "-I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-own-target-headers.hmap" -Xcc "-I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-all-non-framework-target-headers.hmap" -Xcc -ivfsoverlay -Xcc "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/all-product-headers.yaml" -Xcc -iquote -Xcc "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-project-headers.hmap" -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator/include -Xcc "-I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/DerivedSources/i386" -Xcc "-I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/DerivedSources" -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift -emit-module-doc-path "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition~partial.swiftdoc" -Onone -module-name MZFormSheetPresentationController_Swift_Example -emit-module-path "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition~partial.swiftmodule" -serialize-diagnostics-path "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.dia" -emit-dependencies-path "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.d" -emit-reference-dependencies-path "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.swiftdeps" -o "/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.o"

0  swift                    0x000000010c5d910b llvm::sys::PrintStackTrace(__sFILE*) + 43
1  swift                    0x000000010c5d984b SignalHandler(int) + 379
2  libsystem_platform.dylib 0x00007fff8edc4f1a _sigtramp + 26
3  swift                    0x000000010c487833 (anonymous namespace)::Verifier::visitInstruction(llvm::Instruction&) + 6275
4  swift                    0x000000010c4847ce llvm::InstVisitor<(anonymous namespace)::Verifier, void>::visit(llvm::Instruction&) + 2782
5  swift                    0x000000010c47b9a9 (anonymous namespace)::Verifier::verify(llvm::Function const&) + 2153
6  swift                    0x000000010c48de32 (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) + 18
7  swift                    0x000000010c44ba56 llvm::FPPassManager::runOnFunction(llvm::Function&) + 294
8  swift                    0x000000010c44b49d llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) + 189
9  swift                    0x000000010a7e1d67 performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef) + 759
10 swift                    0x000000010a7e0d8b performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, unsigned int) + 1547
11 swift                    0x000000010a7e0f10 swift::performIRGeneration(swift::IRGenOptions&, swift::SourceFile&, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, unsigned int) + 64
12 swift                    0x000000010a6e82e8 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 13704
13 swift                    0x000000010a6e4b4a frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2682
14 swift                    0x000000010a6e11d7 main + 2247
15 libdyld.dylib            0x00007fff8ec0b5c9 start + 1
Stack dump:
0.	Program arguments: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/TransparentViewController.swift /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/ViewController.swift -primary-file /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/CustomTransition.swift /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/AppDelegate.swift /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift/MZFormSheetPresentationController Swift Example/PresentedTableViewController.swift -target i386-apple-ios8.3 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -I /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator -F /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator -F /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator/Pods -g -import-objc-header /Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/MZFormSheetPresentationController/MZFormSheetPresentationController Swift Example-Bridging-Header.h -module-cache-path /Users/vamsee/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-generated-files.hmap -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-own-target-headers.hmap -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/MZFormSheetPresentationController Swift Example-project-headers.hmap -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/DerivedSources/i386 -Xcc -I/Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/vamsee/Development/git/iOS/MZFormSheetPresentationController/Example/Swift -emit-module-doc-path /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition~partial.swiftdoc -Onone -module-name MZFormSheetPresentationController_Swift_Example -emit-module-path /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition~partial.swiftmodule -serialize-diagnostics-path /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.dia -emit-dependencies-path /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.d -emit-reference-dependencies-path /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.swiftdeps -o /Users/vamsee/Library/Developer/Xcode/DerivedData/MZFormSheetPresentationController_Swift_Example-dwwmcdxoqyjhxdcsrnbcroikvtir/Build/Intermediates/MZFormSheetPresentationController Swift Example.build/Debug-iphonesimulator/MZFormSheetPresentationController Swift Example.build/Objects-normal/i386/CustomTransition.o 
1.	Running pass 'Module Verifier' on function '@_TFC47MZFormSheetPresentationController_Swift_Example16CustomTransition34entryFormSheetControllerTransitionfS0_FTCSo33MZFormSheetPresentationController17completionHandlerFT_T__T_'

Command failed due to signal: Segmentation fault: 11

**Comment by danielsaidi** [comment]
As the stack trace says, it does not build due to the CustomTransition.swift file. I did not have time to find what's causing it, but if you comment out both method bodies in the class, the project will build and run.

**Comment by lakamsani** [comment]
It builds and runs if I change line 27 of CustomTransition.swift to force downcast using as! instead of as?

        bounceAnimation.setValue(completionHandler as! AnyObject, forKey: "completionHandler")
