### ISSUE TITLE
Swipe to go back

### ISSUE THREAD

**Issue by danielsaidi** [m1entus/MZFormSheetPresentationController#25]
I love your lib - the simplicity in how to use it and how great it looks is just amazing. So first of all, thanks for that :)

However, I noticed that you cannot perform a left screen edge swipe to go back up the navigation stack. Do you have any idea how to solve this?

**Comment by m1entus** [comment]
Unfortunately, you would have to add your geture directly to MZFormSheetPresentationController or dimming view, check how is done transparent touch, and you would know where to add your gesture

**Comment by danielsaidi** [comment]
Hey, I just replied to my other feature request (I did not want to create issues, but could not find how to post a feature request) regarding a lib that I use that has these features. Check it out here - https://github.com/m1entus/MZFormSheetPresentationController/issues/26#issuecomment-142852157
