### ISSUE TITLE
Swipe to close the modal

### ISSUE THREAD

**Issue by danielsaidi** [m1entus/MZFormSheetPresentationController#26]
While I'm at it, is there any way to dismiss the modals by swiping down on the navigation bar of a modally presented view (you know, like the mail app modals).

**Comment by m1entus** [comment]
It is possible but you would have to implement your own Pan gesture added to MZFormSheetPresentationController/dimming view

**Comment by danielsaidi** [comment]
Thanks for your quick replies :) 

A friend of mine created a modal sheet (https://github.com/danielsaidi/CJTransitionsLab), that I use in an app (you can check it out here - https://itunes.apple.com/app/pinny/id984638325). It has native swipe to go back as well as swipe to close. 

However, I want to use your modal since it looks great and has a bunch of features. I'll try to add the features to your project, but if I find myself hopelessly lost, I'll just hope that you can grab some ideas from CJTransitionsLab :)

**Comment by m1entus** [comment]
Added in MZFormSheetPresentationController 2.0.0.
