### ISSUE TITLE
Init content with Navigation Controller with Root from Viewcontroller (Nib nor Storyboard)

### ISSUE THREAD

**Issue by nhokkuteluv** [m1entus/MZFormSheetPresentationController#27]
I'm using view controller which using nib to as root controller of UINavigationController. Then I use MZFormSheetController to display this navigation controller. But the problem is when I need push a new view controller to this navigation controller, the modal view is disappear (the only left is blur screen). But by your example, I see that you instantiate from storyboard with exist push segue from vc1 -> vc2. So how I can resolve this problem? Any help is really appreciate. Thank in advance. The code like this:

Init by navigation controller (with root controller is orderViewController):

modalNavController = [[UINavigationController alloc] initWithRootViewController:self.orderViewController];
    modalNavController.navigationBarHidden = YES;
    [self initMZPresentationControllerWith:modalNavController];

Then, I want to push vc 2 to this navigation controller:
OptionsDetailViewController *optionsDetailVC = [[OptionsDetailViewController alloc] init];
    optionsDetailVC.options = dishOptions;
    [self.orderViewController.navigationController pushViewController:optionsDetailVC animated:YES];

I tap on cell to push new view controller.By this the modal view is disappear and the rest of it is blur screen. (Figure below)
<img width="378" alt="screen shot 2015-10-10 at 7 47 32 am" src="https://cloud.githubusercontent.com/assets/5270487/10408276/51c4e58a-6f23-11e5-9d65-6c23c4245b38.png">

**Comment by m1entus** [comment]
As i see you are trying to set frame to MZFormSheetPresentationController class instead of your contentView controller, i was checking and everything works fine... Check out yourself:

    UIViewController *vc = [[UIViewController alloc] init];
    vc.view.backgroundColor = [UIColor whiteColor];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:vc];
    MZFormSheetPresentationController *formSheetController = [[MZFormSheetPresentationController alloc] initWithContentViewController:navigationController];

    [self presentViewController:formSheetController animated:YES completion:nil];
