### ISSUE TITLE
multiple custom transitions

### ISSUE THREAD

**Issue by keithics** [m1entus/MZFormSheetPresentationController#29]
is there a way that I can define multiple custom transitions? thank you.

**Comment by m1entus** [comment]
You can override standard ones if you like in the same way as custom

**Comment by keithics** [comment]
that's exactly what I am doing right now. I am hoping we could add multiple custom transition in the future without overriding the defaults. thank you for a prompt reply.

**Comment by m1entus** [comment]
Since 2.0.0 you can create you animator based on native transitioning delegate, this will solve your problem
