### ISSUE TITLE
Vertical center

### ISSUE THREAD

**Issue by rojo69** [m1entus/MZFormSheetPresentationController#30]
I get the same position no matter of the value assigned to shouldCenterVertically.

**Comment by m1entus** [comment]
Have you set self.movementActionWhenKeyboardAppears == MZFormSheetActionWhenKeyboardAppearsDoNothing ?

**Comment by rojo69** [comment]
Haven't altered it, so that seems to be the value.
    "} else if (self.shouldCenterVertically) {" in MSFormSheetPresentation controller evaluates to YES and the y-position is assigned.

**Comment by m1entus** [comment]
Don't see anything wrong here

**Comment by rojo69** [comment]
Isn’t it supposed to center vertically?
Now the view is placed on the upper part of the screen, even without a visible keyboard.

**Comment by m1entus** [comment]
You would have form sheet on the ceter if you make transition and make sure that after your transition view will be on center, on each other case like showing keyboard rotating view frame will change to center

**Comment by m1entus** [comment]
Fixed
