### ISSUE TITLE
Changing transition style after presenting not working

### ISSUE THREAD

**Issue by mkeremkeskin** [m1entus/MZFormSheetPresentationController#31]
Hi;

In MZFormSheetController by changing transition style after presenting the formSheet I can achieve come and go style animations.

For example the below example should come from right of the screen and leaving from left. But in MZFormSheetPresentationController changing transition style not working as before. 

        _formPresentSheet.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyleSlideAndBounceFromRight;
        
        [fromVC presentViewController:_formPresentSheet animated:YES completion:^{
                _formPresentSheet.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStylelideAndBounceFromLeft;                
        }];

I wanna achieve this transition. If this is not possible I think I should use custom transitions. I tried it and could not manage to work it out. If there is a way to do it as I was doing before it would be very handy, if not can you show me a way how to achieve it?

Also `MZFormSheetPresentationTransitionStylelideAndBounceFromLeft` is misspelled.

**Comment by m1entus** [comment]
2.0.0 was designed to use apple guidlines and native transitions using animate transitioning, you cas set @property (nonatomic, strong, null_resettable) id <MZFormSheetPresentationViewControllerAnimatedTransitioning> animatorForPresentationController;
 to animator class which i made with different transition object, and i would recommend this way, but anyway i will try allow to do this

**Comment by mkeremkeskin** [comment]
Thanks for the quick update.
