### ISSUE TITLE
Update contentSize when rotation

### ISSUE THREAD

**Issue by havocked** [m1entus/MZFormSheetPresentationController#32]
Hi ! Thanks for this great library !

I just wanted to know how do you update the frame of the content when the rotate the device ?

Indeed I saw on the 2.0.0 changelog this line:
"Added frame configuration handler which allow you to change frame during rotation and animations"

But no way to see how we can handle this.

Thanks again !

**Comment by havocked** [comment]
Actually I managed to do this:

```swift
let completionHandler:(view: UIView, rect: CGRect) -> CGRect = {
                arg in
                return (CGRectMake(arg.rect.origin.x, arg.rect.origin.x, CGRectGetWidth(splitView.frame) * 0.8, CGRectGetHeight(splitView.frame) * 0.8))
            }

formSheetController.presentationController?.frameConfigurationHandler = completionHandler

```

My problem now is how can i center correctly the view after rotation ?

Thanks Again !

**Comment by m1entus** [comment]
You need to change this values "arg.rect.origin.x, arg.rect.origin.x" to be center of formSheetController.presentationController

**Comment by m1entus** [comment]
I have added example how to modify frame
