### ISSUE TITLE
contentViewSize not working on iPad

### ISSUE THREAD

**Issue by tbaranes** [m1entus/MZFormSheetPresentationController#34]
Everything is working perfectly on iPhone... but I can't get the right frame on iPad (portrait and landscape). It's exactly the same code for the both platform:

```
    [[MZFormSheetPresentationController appearance] setShouldApplyBackgroundBlurEffect:YES];
    [[MZFormSheetPresentationController appearance] setBlurEffectStyle:UIBlurEffectStyleDark];

    KFPurchasePassViewController *purchasePassVC = [[KFPurchasePassViewController alloc] initWithNibName:@"KFPurchasePassViewController" bundle:nil];
    MZFormSheetPresentationViewController *formSheetController = [[MZFormSheetPresentationViewController alloc] initWithContentViewController:purchasePassVC];
    formSheetController.presentationController.contentViewSize = CGSizeMake(300.f, 426.f);
    formSheetController.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyleDropDown;
    formSheetController.presentationController.shouldCenterVertically = YES;
    formSheetController.presentationController.shouldDismissOnBackgroundViewTap = YES;    
    [self presentViewController:formSheetController animated:YES completion:nil];
```

The `KFPurchasePassViewController` is using a xib, but the contraints are the same for iPhone and iPad.

![simulator screen shot 12 nov 2015 10 07 32](https://cloud.githubusercontent.com/assets/1402212/11114639/6503bc62-8926-11e5-9a2e-aa26a4e3d9fa.png)

So, as we can see on the screenshots, the frame isn't the right one, the width is larger....
Any ideas why I'm getting this? Did I miss something?

**Comment by m1entus** [comment]
Probably you made something wrong inside KFPurchasePassViewController, try present empty controller with white background and show me the results, and if you could make simple example with your xib, then i could help you with your problem:

    MZFormSheetPresentationViewController *formSheetController = [[MZFormSheetPresentationViewController alloc] initWithContentViewController:emptyViewController];
    formSheetController.presentationController.contentViewSize = CGSizeMake(300.f, 426.f);
    formSheetController.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyleDropDown;
    formSheetController.presentationController.shouldCenterVertically = YES;
    formSheetController.presentationController.shouldDismissOnBackgroundViewTap = YES;
    [self presentViewController:formSheetController animated:YES completion:nil];

**Comment by m1entus** [comment]
Also you can send me saved session capture from Reveal app which is available since 1.6 version

**Comment by tbaranes** [comment]
Thanks for your quick reply! I just figure out my error: the lateral menu was changing the frame of all the controllers, even if it's a popup... So, my bad. 

Thanks for this library, it's really a great tool :)

**Comment by m1entus** [comment]
Cool, thanks :)
