### ISSUE TITLE
iOS 9 autolayout on custom sizing view

### ISSUE THREAD

**Issue by hebbian** [m1entus/MZFormSheetPresentationController#37]
Thanks for great library and excellent support.

But in iOS9, the autolayout looks broken (look at the textview) especially on the second view. This problem occurs once I upgraded my device to iOS9 (I tested it in simulator), and it fix itself after some event like rotating device or drag the view around (like you want to close it). Any explanation? 

![image]
(https://s3-ap-southeast-1.amazonaws.com/uploads-ap.hipchat.com/282999/1780031/rdxhPDQfB3NwsHy/Simulator%20Screen%20Shot%20Nov%2021%2C%202015%2C%2010.13.27.png)

Thanks

**Comment by m1entus** [comment]
Thanks for support, good catch, i forgot to setup final frame to target view controller
