### ISSUE TITLE
Is there a way to update contentViewSize manually?

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [m1entus/MZFormSheetPresentationController#38]
I use this viewController to display a table whose data is requested after displayed. Is there a way I can update contentViewSize after reload data of table? Thanks.
BTW, This repo is great!

**Comment by m1entus** [comment]
If you set contentViewSize manualy then it will update contentViewSize, you can get reference using 

@interface UIViewController (MZFormSheetPresentationViewController)
- (nullable MZFormSheetPresentationViewController *)mz_formSheetPresentingPresentationController;
- (nullable MZFormSheetPresentationViewController *)mz_formSheetPresentedPresentationController;
@end

You can even use MZFormSheetPresentationContentSizing protocal as in Objective-C example, and then call :

 MZFormSheetPresentationController *presentationController = (id)targetViewController.mz_formSheetPresentingPresentationController.presentationController;
    [UIView animateWithDuration:[self transitionDuration:transitionContext] delay:0 options:UIViewAnimationOptionBeginFromCurrentState animations:^{
        [presentationController layoutPresentingViewController];
    } completion:nil];

As you see, there is many ways to do this...
