### ISSUE TITLE
Status bar is bright when contentViewController is presented

### ISSUE THREAD

**Issue by TruthDerek** [m1entus/MZFormSheetPresentationController#39]
The status bar style is `.LightContent`, I hope it will be dim when when `contentViewController` is presented. However, it is bright which seems like highlighted with a dim background.
Any advice?

**Comment by TruthDerek** [comment]
I know one of the solutions is to create a new `UIWindow` and set its `windowLevel` to `UIWindowLevelStatusBar`, but I think it should be done in `MZFormSheetPresentationController`.

**Comment by m1entus** [comment]
Lol... Of course not, you need to just override preferredStatusBarStyle in your contentViewController and make sure that call setNeedsStatusBarAppearanceUpdate

**Comment by TruthDerek** [comment]
I have tried your suggestion and realized you have misunderstood my question. I didn't mean changing `preferredStatusBarStyle` by saying `dim`. I want the status bar to be covered by a transparent black view just like the background view instead of above the view. Do you get my point?

**Comment by m1entus** [comment]
On Apple Guidlines status bar is always on the top, MZFormSheetPresentationController is using presentation controllers which is recommended by apple and not using UIWindow presentation as MZFormSheetController and it won't in future.

**Comment by TruthDerek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10831007/11364834/cee6fdd6-92dd-11e5-917e-da260b73bbbb.png)
![untitled 2](https://cloud.githubusercontent.com/assets/10831007/11364836/cf36f098-92dd-11e5-9438-14a31e6fc62b.png)
The effect I want is the second one. I am sorry if I didn't express clearly before. I think it is possible because in your demo it is the second effect.

**Comment by m1entus** [comment]
In my demo is the first one, and as i said i am using native way for presenting view controllers, apple is doing in this way so do i.

**Comment by TruthDerek** [comment]
Ok..., thank you anyway. You must be mad at me right now. So sorry.

**Comment by eliburke** [comment]
I don't think he's mad. I think he's trying to tell you that what you want can't be done using automatic behavior with MZFormSheetPresentationController. It could be done in the older version using MZFormSheetController, which used UIWindow presentation.

Perhaps you can accomplish what you want by tinting the status bar in the completion blocks for showing and dismissing your modal view?

**Comment by m1entus** [comment]
Yep, i am not mad, just wanted to tell you that this is not how Apple designed their presenters, and even popover controller have status bar always on top. Good catch @eliburke , you can always make screenshot of status bar window, and then add it below dimming view in form sheet presentation controller, and hide status bar. You will get this effect.
