### ISSUE TITLE
Cocoapods install fails

### ISSUE THREAD

**Issue by siburb** [m1entus/MZFormSheetPresentationController#40]
It looks like the updated podspec file is not tagged for the latest version.

Not sure if that is the only problem, but we get the following every time we try to install this pod:

```
[!] Unable to satisfy the following requirements:

- `MZFormSheetPresentationController (~> 2.1.3)` required by `Podfile`
```

**Comment by m1entus** [comment]
Not sure where the problem is, but i was also getting this error for many different pods... Try pod update MZFormSheetPresentationController.

**Comment by siburb** [comment]
Because it hasn’t been installed previously (I’ve used MZFormSheetController up until now), I get this:




```

[!] The `MZFormSheetPresentationController` Pod is not installed and cannot be updated


```




Apart from that, no matter whether I use `pod install` or `pod update`, I still get the same “Unable to satisfy the following requirements” message.




I’m not getting this for any other pods, and this project has about 40 of them listed in the podfile!

**Comment by m1entus** [comment]
MZFormSheetPresentationController is requirement iOS 8 and above, check your deploment target maybe?

**Comment by siburb** [comment]
That's exactly it Michal - thanks for your help and sorry to waste your time!

I'm very much hoping to stop supporting iOS7 with this project very soon!

**Comment by m1entus** [comment]
Cool, no problem :)
