### ISSUE TITLE
interactivePanGestureDissmisalDireciton retains Content View Controller

### ISSUE THREAD

**Issue by imton** [m1entus/MZFormSheetPresentationController#41]
Hey!

Awesome work here.

Be careful that setting ```interactivePanGestureDissmisalDireciton``` is retaining the controller presented and do never dealloc. 

I solved by adding this in viewDidDissapear

````obj-c
    [self removeEdgeDismissalPanGestureRecognizer];
    [self removePresentaingViewDismissalPanGestureRecognizer];
````

Best

**Comment by imton** [comment]
ok.. maybe it was (and/or) the interactive ```transitionContext``` being strong 

I made it weak and dealloc is working again

````obj-c
@property (nonatomic, weak) id<UIViewControllerContextTransitioning> transitionContext;
````

**Comment by m1entus** [comment]
Thanks, fixed.
