### ISSUE TITLE
Question with autolayout: adaptative size

### ISSUE THREAD

**Issue by Vinzius** [m1entus/MZFormSheetPresentationController#42]
Hello,

First, thank you for this library.
I have a question regarding its use with autolayout.

I don't see how to go around the `contentViewSize` of MZFormSheetPresentationController in order to let autolayout handle the sizes.

Example 1: I have a view with a label, text = "hello world". I pin the label to the its superview edges. So I expect the presented view to have a small size.

Example 2: I want the width of my view to be 80% of the screen.

Thanks!

**Comment by m1entus** [comment]
Autolayout will not be available to handle contentViewSize, even on apple controls for exaple popoverPresentationController you are not able to do it. You can calculate label size and manually change content size of presenter controller

**Comment by Vinzius** [comment]
It was my fear, thanks. Too bad :-(

I like to use autolayout (as Apple is pushing for it), but this kind of problem doesn't help...
