### ISSUE TITLE
MZAppearance/MZAppearance.h' file not found

### ISSUE THREAD

**Issue by irfanzsheikh** [m1entus/MZFormSheetPresentationController#49]
I am getting this error while importing into my xcode. I have imported swift project.

/Users/myname/Downloads/MZFormSheetPresentationController-master/MZFormSheetPresentationController/MZFormSheetPresentationController.h:27:9: error: 'MZAppearance/MZAppearance.h' file not found
#import <MZAppearance/MZAppearance.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/myname/Downloads/MZFormSheetPresentationController-master/MZFormSheetPresentationController/MZFormSheetPresentationController Swift Example-Bridging-Header.h'

Please tell me how can I resolve this issue ?

**Comment by irfanzsheikh** [comment]
Well the issue hasn't resolved it yet.

**Comment by m1entus** [comment]
But thisissue is because you don't know how to import it and not library itself. Use cocoapods and all magic will be done without necessary knowledge

**Comment by irfanzsheikh** [comment]
i have already imported the files now but still I am getting this error...

**Comment by m1entus** [comment]
As you see example project is working fine...

**Comment by irfanzsheikh** [comment]
yeah I understand there is nothing wrong in your project but as I wasn't able to get help to any other platform so I come here. anyway Its okay..

**Comment by eliburke** [comment]
This could be something Swift specific, but for myObjective C project (which doesn't use CocoaPods) I had to do the following:
* Check out BOTH the MZFormSheetController and MZAppearance projects 
* Add both directories to the project's Header Search Path. In my case I have:
Externals/MZFormSheetController/MZFormSheetController
Externals/MZAppearance

**Comment by keehun** [comment]
I also had to drag in the Xcode Projects into my workspace. (I did not want to use cocoa pods for a specific reason)
