### ISSUE TITLE
Can you give some info on how to use this with Swift?

### ISSUE THREAD

**Issue by camill-a** [m1entus/MZFormSheetPresentationController#51]
I installed the framework using cocoaPods , but I still cannot import nor create a bridging header. Could you add some direction in the Readme.md?

**Comment by YOnoda** [comment]
+1 for this question. I tried to import it with the following Bridging-Header but still got `Could not build module` error.

    #import <MZFormSheetPresentationController/MZFormSheetPresentationController.h> // error
    #import <MZAppearance/MZAppearance.h> // OK

I wish there were some instructions on README.

**Comment by m1entus** [comment]
Use CocoaPods if you not sure how to integrate it
