### ISSUE TITLE
Callbacks based on interactivePanGestureDissmisalDirection

### ISSUE THREAD

**Issue by avicooper1** [m1entus/MZFormSheetPresentationController#52]
Is it possible to provide different callbacks for each direction that a user could swipe the view? I would like to implement functionality that would dismiss the view if swiped down, but save some entered information if swiped up.

Thanks.

**Comment by m1entus** [comment]
You can subclass MZFormSheetPresentationViewControllerInteractiveAnimator, expose currentDirection property and handle updateInteractiveTransition:(CGFloat)percentage
