### ISSUE TITLE
Bug in your project

### ISSUE THREAD

**Issue by luigibros** [m1entus/MZFormSheetPresentationController#54]
Hi i downloaded your project to test it out, unfortunately when i tried to compile it i ran into a bug, this is the error:
ld: library not found for -lPods-MZAppearance
clang: error: linker command failed with exit code 1 (use -v to see invocation)
i hope to be able to test it soon

**Comment by m1entus** [comment]
Use older Pods than 1.0.0 beta.x, projects are not updated for beta Pods or just delete -lPods-MZAppearance and link correct one which was generated by new cocoapods.
