### ISSUE TITLE
Animating changes in contentViewFrameForPresentationController

### ISSUE THREAD

**Issue by jeffblake** [m1entus/MZFormSheetPresentationController#55]
When I add cells into my table view, I am able to correctly use 

````
- (CGRect)contentViewFrameForPresentationController:(MZFormSheetPresentationController *)presentationController currentFrame:(CGRect)currentFrame
````

to make the change in height. However, its a little abrupt. I was hoping to be able to animate the change in height? Is that possible? I'm combed the source code but can't find anything.

**Comment by m1entus** [comment]
You must call:

animateWithDuration:1.0 delay:0 options:UIViewAnimationOptionBeginFromCurrentState animations:^{
        [presentationController layoutPresentingViewController];
    } completion:nil]; to be able manually layout controller

**Comment by m1entus** [comment]
MZFormSheetPresentationController *presentationController = self.mz_formSheetPresentingPresentationController
