### ISSUE TITLE
Setting MZFormSheetPresentationTransitionStyleSlideFromTop causes janky dismiss animation

### ISSUE THREAD

**Issue by jeffblake** [m1entus/MZFormSheetPresentationController#56]
````
formSheetController.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyleSlideFromTop;
````

It looks great when appearing, but when dismissing, it goes up, then down, then spazzes out.

**Comment by m1entus** [comment]
Can you prepare sample of it? Because on example looks fine and always you can create custom animation

**Comment by jeffblake** [comment]
it wouldn't be feasible to produce a sample... its ok I'm using a different transition.
