### ISSUE TITLE
How to make the modal background transparent.

### ISSUE THREAD

**Issue by omarojo** [m1entus/MZFormSheetPresentationController#57]
Is there a way to present a modal that instead of having a white background as it is by default. It has a transparent or blurred background ? currently the blurred option in MZ just blurs the outside background of the modal.

I intent to have a ViewController that is showing a camera feed, and I would like to present a modal on top of that, with blurred background so I can still see the camera refreshing in the back.

**Comment by m1entus** [comment]
Check the Objective-C example there is one case for that and probably you are interested to present using style: OverCurrentContext on MZFormSheet..

**Comment by omarojo** [comment]
Thanks, I ended up using the blurred effect, changed the size of the presented view controller, and setting to 0 the top inset. These are all MZForm settings. But indeed I need to configure the "overCurrentContext" of the presented view controller to have its background transparent as clear color.
