### ISSUE TITLE
Dismiss on tapping background view

### ISSUE THREAD

**Issue by onomated** [m1entus/MZFormSheetPresentationController#62]
Don't know what I'm missing, but I cannot dismiss the presentation controller by tapping the background view.  I don't have a navigation controller, just a single view controller with an embedded scrollview. Looks like there used to be a property for this `shouldDismissOnBackgroundViewTap ` that no longer exists.  Do I have to implement this by calling dismiss?  I bet the answer is staring me right in the face...

**Comment by m1entus** [comment]
It still exists but on presentationController, check example project and you will find how to do this: https://github.com/m1entus/MZFormSheetPresentationController/blob/master/MZFormSheetPresentationController/MZFormSheetPresentationController.h#L67

**Comment by onomated** [comment]
Thanks!
