### ISSUE TITLE
Question: how to install?

### ISSUE THREAD

**Issue by oferRounds** [m1entus/MZFormSheetPresentationController#63]
After adding the source files I get the following error:

Library not loaded: @rpath/MZAppearance.framework/MZAppearance
[...]
Reason: image not found

**Comment by m1entus** [comment]
Check this, https://github.com/m1entus/MZFormSheetPresentationController/issues/49. You need to also import MZAppearance source files

**Comment by oferRounds** [comment]
Cool - thanks!
