### ISSUE TITLE
Headers are not exposed correct when using with Carthage

### ISSUE THREAD

**Issue by fatuhoku** [m1entus/MZFormSheetPresentationController#68]
1. Can't import & use `MZFormSheetPresentationViewController`.

```objc
#import <MZFormSheetPresentationController/MZFormSheetPresentationViewController.h> // THIS FAILS
```

2. `MZTransition.h` isn't found.

```objc
#import <UIKit/UIKit.h>
#import <MZAppearance/MZAppearance.h>
#import "MZTransition.h"  // import not found.

typedef void(^MZFormSheetPresentationControllerTransitionBeginCompletionHandler)(UIViewController * __nonnull presentingViewController);
```

**Comment by m1entus** [comment]
I am waiting for correct PR because i am not using Carthage in any of my project, so this is not necessary for me

**Comment by eliburke** [comment]
I just got bitten by this as well. Perhaps you can update the README.md to indicate that Carthage support is not yet working?

As for the problem I think it is maybe not with Carthage, but the settings on the MZFormSheetPresentationController framework. I've never set up a framework myself, but steps 4 and 5 of [this guide](http://www.insert.io/frameworkios8xcode6/) and [Ray's tutorial](https://www.raywenderlich.com/65964/create-a-framework-for-ios) make me think that you need to make more of the internal headers public, and perhaps change the import lines to include the framework folder like this: `#import <MZFormSheetPresentationController/MZTransition.h>` 

![screen shot 2016-04-20 at 11 03 37 am](https://cloud.githubusercontent.com/assets/2371768/14679425/d1315810-06e7-11e6-9b00-35ce6c33b1c9.png)

**Comment by livyathan** [comment]
I'm having the same issue. I also have no idea how to solve it, I just started to use carthage yesterday.

**Comment by eliburke** [comment]
I've just created pr #85 to address this issue. I added 5 new headers to the public header list: 
- MZTransition.h
- MZFormSheetPresentationViewController.h
- MZFormSheetPresentationContentSizing.h
- MZFormSheetPresentationViewControllerAnimatedTransitioning.h 
- MZFormSheetPresentationViewControllerInteractiveTransitioning.h

I also had to change some of the imports to use < > instead of " ".

I did not verify that CocoaPods still works so it would be great if someone could check that.

**Comment by m1entus** [comment]
Marged #85

**Comment by eliburke** [comment]
Just a final comment in case anyone lands here. As of right now, the correct framework import is `#import <MZFormSheetPresentationController/MZFormSheetPresentationViewController.h>`

@m1entus I didn't think to update README.md to add this-- would you mind? Or I can submit another PR.

**Comment by m1entus** [comment]
If you can update README would be great, because i don't use Carthage and don't have experience with it.

**Comment by eliburke** [comment]
Sure thing, #86 
Thanks for merging, I appreciate it.

**Comment by KHellkvist** [comment]
@eliburke thank you for fixing this, part of it was my mess, didn't really get it to work when I added the Carthage support a while back.

There is still some an issue with this when I use it, i get these 2 warnings:
```
Umbrella header for module 'MZFormSheetPresentationController' does not include header 'MZBlurEffectAdapter.h'
```
```
Umbrella header for module 'MZFormSheetPresentationController' does not include header 'MZFormSheetPresentationController Swift Example-Bridging-Header.h'
```

**Comment by eliburke** [comment]
Hey @KHellkvist I wasn't sure (especially about the swift bridging header) if I should throw everything in there or not, so I erred on the side of only including the headers I needed for my project. :)

**Comment by KHellkvist** [comment]
@eliburke I'm working on a PR for this since I don't like the warnings I get when I use this.
I've only added the `MZBlurEffectAdapter`for now. Do you have any input on if it really should be all of the headers? 
https://github.com/KHellkvist/MZFormSheetPresentationController/commit/f7b356f345a1b91410181d228855552ec0431c76

**Comment by eliburke** [comment]
@KHellkvist I'd say if you get a warning for both, add both. If it doesn't blow up, 👍
