### ISSUE TITLE
MZFormSheetPresentationController UIBlurEffectStyleDark seems to be using UIBlurEffectStyleLight

### ISSUE THREAD

**Issue by lostirc** [m1entus/MZFormSheetPresentationController#7]
In version 1.0.1 it looks like setting blurEffectStyle to UIBlurEffectStyleDark still uses UIBlurEffectStyleLight. I've also seen a possibly unrelated issue where setting contentViewCornerRadius = 0 also has no effect.

Thanks again

**Comment by m1entus** [comment]
Thanks for reporting, fixed.
