### ISSUE TITLE
Current Frame usage in Swift

### ISSUE THREAD

**Issue by sinanulkuatam** [m1entus/MZFormSheetPresentationController#87]
Hello!

Quick question, when using the content view frame function in Swift 

```
func contentViewFrameForPresentationController(presentationController: MZFormSheetPresentationController, currentFrame: CGRect) -> CGRect {
        currentFrame.size.height = 450
        currentFrame.origin.y = 20
        return currentFrame
 }
```

I am getting the following issue

> Cannot assign to property: 'currentFrame' is a 'let' constant

Is there a way this can be a var instead of a let, or am I missing something?

**Comment by m1entus** [comment]
You just need to do, var currentFrame = currentFrame, and you will be able to change it, in Swift 3 they will discard var in parameters anyway...

**Comment by sinanulkuatam** [comment]
@m1entus got it, thanks!
