### ISSUE TITLE
Attempt to present..whose is not in the window hierarchy

### ISSUE THREAD

**Issue by mbaldinazzo** [m1entus/MZFormSheetPresentationController#89]
Hi, I have this problem in my app:
[link](http://stackoverflow.com/questions/37830043/view-over-view-hierarch-breaks-hierarchical)
How can I do to solve it?
Thanks in advance.

**Comment by m1entus** [comment]
I answered you at stackoverflow

**Comment by mbaldinazzo** [comment]
@m1entus I saw and I tried it but I still get the hierarchy error
