### ISSUE TITLE
imported but MZAppearance/MZAppearance file not found

### ISSUE THREAD

**Issue by mirzadelic** [m1entus/MZFormSheetPresentationController#9]
Getting this error when included these lines in header file:
```
#import "MZFormSheetPresentationController.h"
#import "MZFormSheetPresentationControllerSegue.h"
```

error:
```
MZFormSheetPresentationController/MZFormSheetPresentationController.h:28:9: 'MZAppearance/MZAppearance.h' file not found
```

**Comment by m1entus** [comment]
You need to download dependencies, MZAppearance and JGMethodSwizzler or use Cocoapods

**Comment by mirzadelic** [comment]
I can't use `use_framework!` will this be problem?

**Comment by m1entus** [comment]
If you are using framework you don't need to #import <MZFormSheetPresentationController/MZFormSheetPresentationController.h> linke this ?

**Comment by mirzadelic** [comment]
Can't run application:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Storyboard (<UIStoryboard: 0x7fe160e2f530>) doesn't contain a view controller with identifier 'DetailViewController''
```
But i have `DetailViewController`.

**Comment by m1entus** [comment]
Lol, but you don't have identifier set to it.....
