### ISSUE TITLE
Preserve presenter frame

### ISSUE THREAD

**Issue by tbaranes** [m1entus/MZFormSheetPresentationController#94]
When presenting a `formSheet`, it's using the screen frame instead of the `viewController`'s one. Is there any way to present a `formSheet` with the presenter frame?

**Comment by m1entus** [comment]
You must use OverCurentContext presentation to be able to present over viewController frame, in obj-c example you will find sample

**Comment by tbaranes** [comment]
I'm already using `.OverCurrentContext` to present modals, it's working when it's a `UIViewController` alone, but fails when used with `MZFormSheetPresentationController`.

Here a sample code that doesn't work as expected:

```
let vc = ViewController()
// Customisations...
vc.formSheet.modalPresentationStyle = .OverCurrentContext
self.presentViewController(vc.formSheet, animated: true, completion: nil)
```

Where `self` is a viewController on the screen but not taking the fullscreen, just half of it.  Am I missing something?

**Comment by m1entus** [comment]
I am not sure what you are trying to do, present formSheet over formSheet over currentContext ? This would not be possible because MZFormSheetPresentationController defines his own presentation context, you could present normal UIViewController over MZFormSheetPresentationController and set OverCurrentContext then you will be able to present over presented container

**Comment by m1entus** [comment]
```
- (void)modalPresentationInsideFormSheetController {
    UINavigationController *navigationController = [self formSheetControllerWithNavigationController];
    MZFormSheetPresentationViewController *formSheetController = [[MZFormSheetPresentationViewController alloc] initWithContentViewController:navigationController];
    formSheetController.presentationController.shouldDismissOnBackgroundViewTap = YES;
    formSheetController.presentationController.portraitTopInset = 10;
    
    // This need to be set because presented modaly view need to be masked
    formSheetController.view.layer.masksToBounds = YES;
    
    [self presentViewController:formSheetController animated:YES completion:^{
        UIViewController *controller = [self.storyboard instantiateViewControllerWithIdentifier:@"TransparentViewController"];
        controller.modalPresentationStyle = UIModalPresentationOverCurrentContext;
        controller.view.layer.cornerRadius = navigationController.view.layer.cornerRadius;
        
        // Imporatant is to present view controller from navigationController
        // because UITransitionView will be added to navigationController view !!!
        [navigationController presentViewController:controller animated:YES completion:nil];
    }];
}
```

**Comment by tbaranes** [comment]
Sorry that I'm not clear, here a visual example, it will probably help to explain myself:

![ipad portrait](https://cloud.githubusercontent.com/assets/1402212/16427739/f870b43a-3d6e-11e6-83af-0f8a2f8b269b.png)

Let's say that each color (black, white, red, and blue) is an independent `ViewController`. If I present a controller (a simple black overlay) over the red one, it should something like this:

![ipad portrait](https://cloud.githubusercontent.com/assets/1402212/16427867/b96a7f90-3d6f-11e6-810e-ea6214819f13.png)

The `presentingVC` is keeping the same frame as the `presenterVC` instead of using all the screen. 

> I am not sure what you are trying to do, present formSheet over formSheet over currentContext ? This would not be possible because MZFormSheetPresentationController defines his own presentation context

I suppose that is not possible? I know it's possible by presenting myself the controller, but `MZFormSheetPresentationController` is really useful 😁

**Comment by m1entus** [comment]
Yes probably in current implementation it is not possible `MZFormSheetPresentationController` works more like popover or alertController rather than presentation over current context, but probably you could easly write own UIPresentationController or subclass from MZFormSheetPresentationController and provide container frame as your (red) viewController frame

**Comment by tbaranes** [comment]
I see, thanks for your response!
