### ISSUE TITLE
MZPresentationController Crash on iOS8

### ISSUE THREAD

**Issue by Anilkr91** [m1entus/MZFormSheetPresentationController#95]
I am using mzpresentationcontroller `MZFormSheetPresentationController` (2.4.0) it is working good in ios 9 but crashing in ios8.

This is myCode i am using in prepare for segue

    let presentationSegue = segue as! MZFormSheetPresentationViewControllerSegue
    let navigationController = presentationSegue.formSheetPresentationController.contentViewController as! GetStartedAlertViewController
    let formSheetController = MZFormSheetPresentationViewController(contentViewController: navigationController)
    formSheetController.presentationController?.contentViewSize = CGSizeMake(280, 350)
    formSheetController.presentationController?.shouldCenterVertically = true
    formSheetController.contentViewControllerTransitionStyle = .Bounce
    formSheetController.presentationController?.shouldDismissOnBackgroundViewTap = true
    self.presentViewController(formSheetController, animated: true, completion: nil)

 i am getting the error stated below.

> Terminating app due to uncaught exception
> 'NSInvalidArgumentException', reason:
> '-[FormSheetPresentationViewControllerSegue
> setDestinationContainmentContext:]: unrecognized selector sent to
> instance 0x7fa6b4576620
> 
> *** First throw call stack: ( 	0   CoreFoundation                      0x0000000107decf35 __exceptionPreprocess + 165   	1   libobjc.A.dylib 
> 0x000000010b729bb7 objc_exception_throw + 45   	2   CoreFoundation    
> 0x0000000107df404d -[NSObject(NSObject) doesNotRecognizeSelector:] +
> 205   	3   CoreFoundation                      0x0000000107d4c27c
> ___forwarding___ + 988   	4   CoreFoundation                      0x0000000107d4be18 _CF_forwarding_prep_0 + 120   	5   UIKit           
> 0x000000010a1fd0bd -[UIStoryboardPushSegueTemplate
> segueWithDestinationViewController:] + 93   	6   UIKit                
> 0x000000010a18e6dc -[UIStoryboardSegueTemplate _perform:] + 87   	7  
> Rswift                              0x000000010987c624
> _TTOFCSo16UIViewController26performSegueWithIdentifierfTSS6senderGSqPs9AnyObject___T_
> + 68   	8   Rswift                             0x000000010987c438 _TTWCSo16UIViewController6Rswift18SeguePerformerTypeS0_FS1_26performSegueWithIdentifierfTSS6senderGSqPs9AnyObject___T_
> + 72   	9   Rswift                              0x000000010987c4d5 _TFE6RswiftPS_18SeguePerformerType26performSegueWithIdentifieru0_rfTGVS_25StoryboardSegueIdentifierqd__xqd_0__6senderGSqPs9AnyObject___T_
> + 133   	10  TapHeal                             0x0000000104ad5a25 _TFC7TapHeal18HomeViewController12bannerTappedfPs9AnyObject_T_ + 4997   	11  TapHeal                             0x0000000104ad5a86
> _TToFC7TapHeal18HomeViewController12bannerTappedfPs9AnyObject_T_ + 54   	12  UIKit                               0x0000000109fef2e6
> _UIGestureRecognizerSendActions + 262   	13  UIKit                               0x0000000109fedf89 -[UIGestureRecognizer
> _updateGestureWithEvent:buttonEvent:] + 532   	14  UIKit                               0x0000000109ff2ba6 ___UIGestureRecognizerUpdate_block_invoke662 + 51  
> 	15  UIKit                               0x0000000109ff2aa2
> _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 254   	16  UIKit                               0x0000000109fe8b1d
> _UIGestureRecognizerUpdate + 2796   	17  UIKit                               0x0000000109c82ff6 -[UIWindow _sendGesturesForEvent:] + 1041   	18 
> UIKit                               0x0000000109c83c23 -[UIWindow
> sendEvent:] + 667   	19  UIKit                              
> 0x0000000109c509b1 -[UIApplication sendEvent:] + 246 	20  UIKit       
> 0x0000000109c5da7d _UIApplicationHandleEventFromQueueEvent + 17370  
> 	21  UIKit                               0x0000000109c39103
> _UIApplicationHandleEventQueue + 1961   	22  CoreFoundation                      0x0000000107d22551
> __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17   	23  CoreFoundation                      0x0000000107d1841d
> __CFRunLoopDoSources0 + 269   	24  CoreFoundation                      0x0000000107d17a54 __CFRunLoopRun + 868   	25  CoreFoundation         
> 0x0000000107d17486 CFRunLoopRunSpecific + 470   	26  GraphicsServices 
> 0x000000010c9679f0 GSEventRunModal + 161   	27  UIKit                 
> 0x0000000109c3c420 UIApplicationMain + 1282   	28  TapHeal            
> 0x0000000104bcde42 main + 114   	29  libdyld.dylib                    
> 0x000000010c07c145 start + 1   ) libc++abi.dylib: terminating with
> uncaught exception of type NSException

**Comment by m1entus** [comment]
```
'NSInvalidArgumentException', reason:
'-[FormSheetPresentationViewControllerSegue
setDestinationContainmentContext:]: 
```-> On storyboard you should use `MZFormSheetPresentationViewControllerSegue` class insted of `FormSheetPresentationViewControllerSegue`

**Comment by Anilkr91** [comment]
Thanks for the help .. It worked!!

**Comment by gsanctussy** [comment]
Thanks it's worked for me too !!
