### ISSUE TITLE
Xcode 8 (beta 3) Warning: Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'MZPresentationSlideBounceFromRightTransition *const __strong'

### ISSUE THREAD

**Issue by funnel20** [m1entus/MZFormSheetPresentationController#98]
After running Xcode 8 beta 3 and upgrading my project settings to the recommended settings as suggested by Xcode, I get 5 warnings:
_Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'MZPresentationSlideBounceFromRightTransition *const __strong'_

These lines assign `self` to the animation delegate.
The solution is to define the CAAnimationDelegate in each of the transition interfaces, e.g.:
```
@interface MZPresentationSlideBounceFromLeftTransition : MZTransition <CAAnimationDelegate>
@end
```

**Comment by naveenshan01** [comment]
For me its not goes off after adding the <CAAnimationDelegate>, So I did a (id) type cast before setting self to delegate. I know its not a proper way but its a time saver for some others.
