### ISSUE TITLE
Center FormSheet in Screen?

### ISSUE THREAD

**Issue by appcelerate** [m1entus/MZFormSheetPresentationController#99]
It is possible to center the FormSheet in the middle of the Screen :) ?

**Comment by m1entus** [comment]
MZFormSheetPresentationController ->

/**
 Center form sheet vertically.
 By default, this is NO
 */
@property (nonatomic, assign) BOOL shouldCenterVertically MZ_APPEARANCE_SELECTOR;

Set it to true, or change default behaviour using: [[MZFormSheetPresentationController set ShouldCenterVerticallyappearance: YES]

**Comment by appcelerate** [comment]
@m1entus Thanks!
